DEFAULT_LLM_MODEL = "gemma4"
DEFAULT_VISION_MODEL = "qwen2.5vl:7b"
DEFAULT_VISION_ENABLED = True

DEFAULT_PLANNER_MODEL = "qwen2.5:1.5b"
DEFAULT_PLANNER_MAX_QUERIES = 3
DEFAULT_PLANNER_TIMEOUT = 30.0

DEFAULT_PDF_PARSER_MODE = "hybrid"
DEFAULT_DOCLING_ACCELERATOR = "auto"
DEFAULT_ASSET_TRIGGERS = "auto"
DEFAULT_ASSET_DIR = "db/assets"
DEFAULT_CODE_ENRICHMENT = True
DEFAULT_FORMULA_ENRICHMENT = True

DEFAULT_OCR_BACKEND = "rapidocr"
DEFAULT_OCR_LANGS = ("english",)
DEFAULT_OCR_FORCE_FULL_PAGE = True
DEFAULT_OCR_BITMAP_AREA_THRESHOLD = 0.05
DEFAULT_RAPIDOCR_BACKEND = "onnxruntime"
DEFAULT_TESSERACT_CMD = "tesseract"
DEFAULT_TESSERACT_DATA_PATH = ""
DEFAULT_TESSERACT_PSM = None

SUPPORTED_OCR_BACKENDS = ("auto", "rapidocr", "tesseract_cli", "tesseract", "easyocr")
SUPPORTED_RAPIDOCR_BACKENDS = ("onnxruntime", "openvino", "paddle", "torch")
